# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Outlook â†” Google Calendar Sync
title: OGCS
email: ogcs@paulwoolcock.co.uk
description: #> # this means to ignore newlines until "baseurl:"
  Sync your Outlook and Google calendars securely and for free!
  Can include meeting attendees, reminders, full description and more.
  Ideal for liberating your corporate Exchange calendar, making it available
  on any of your devices with access to Google Calendar.
  No install necessary, works behind web proxies and actively developed.
baseurl: "/OutlookGoogleCalendarSync" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: OGcalsync
github_username:  phw198

google_analytics: UA-19426033-4

# Current software releases
show_alpha_downloads: true
beta-exe: "https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.6.0-beta/Setup.exe"
beta-zip: "https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.6.0-beta/Portable_OGCS_v2.6.0.zip"
alpha-exe: "https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.6.4-alpha/Setup.exe"
alpha-zip: "https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.6.4-alpha/Portable_OGCS_v2.6.4.zip"

# Build settings
markdown: kramdown
#theme: minima
theme: jekyll-theme-architect
plugins:
  - jekyll-feed
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
#  - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
  - jekyll-architect-theme.gemspec
