# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Outlook â†” Google Calendar Sync
title: Outlook Google Calendar Sync - OGCS
email: ogcs@paulwoolcock.co.uk
description: #> # this means to ignore newlines until "baseurl:"
  Sync your Outlook and Google calendars securely and for free!
  Can include meeting attendees, reminders, full description and more.
  Ideal for liberating your corporate Exchange calendar, making it available
  on any of your devices with access to Google Calendar.
  No install necessary, works behind web proxies and actively developed.
# baseurl: "/OutlookGoogleCalendarSync" # needed when not using custom domain (ie phw198.github.io/<baseurl>)
baseurl: 
# url: "https://phw198.github.io" # the base hostname & protocol for your site, e.g. http://example.com
url: https://www.outlookgooglecalendarsync.com
github-repo: https://github.com/phw198/OutlookGoogleCalendarSync

twitter_username: OGcalsync
github_username:  phw198

google_analytics: UA-19426033-4
google_ad_client: ca-pub-5710461137665920
# google_ad_testing: "on"
google_ad_testing: "off"

# Current software releases
show_alpha_downloads: true
beta-version: 2.10.0
beta-release-date: Jul-2023
alpha-version: 2.10.1
alpha-release-date: Aug-2023

# Build settings
markdown: kramdown
#theme: minima
theme: jekyll-theme-architect
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
  
#github-pages (163) still depends on jemoji (= 0.8.1) not 0.11.1 where this is hopefully fixed?
#Once fixed, this can be removed.
#Also might be a bug with bundler-2.0.2 not updating things properly.
emoji:
  src: "https://github.githubassets.com/images/icons/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - jekyll-architect-theme.gemspec
  - src
  - _posts/2014-04-06-welcome-to-jekyll.markdown
